export const objReceipts = [
  {
    id: 1,
    auth0_id: '1',
    name: 'TV',
    image: '',
    purchase_date: '02 - 04 - 2019',
    store: 'Smiths City',
    price: 2600,
    category_id: 2,
    note: '',
  },
]

export const fakeClientReceipts = [
  {
    id: 1,
    auth0_id: 'auth0|something',
    username: 'Raf',
    name: 'Drill',
    image: JSON.stringify({
      url: 'http://res.cloudinary.com/receipt-keepers/image/upload/v1658051820/eitbxs4xkecu9xgf9zaf.jpg',
      public_id: 'eitbxs4xkecu9xgf9zaf',
      signature: '2f91fa2de7f47078e925fd0c62e58cd0e7d54103',
    }),
    purchaseDate: new Date(10 / 04 / 2021),
    store: 'Bunnings',
    price: 1200,
    categoryId: 1,
    categoryType: 'Tools',
    note: 'Powerful drill',
    warrantyId: 1,
    expiryDate: new Date(10 / 10 / 2021),
    warrantyPeriod: 6,
    warrantyPeriodUnit: 'month(s)',
  },
  {
    id: 2,
    auth0_id: 'auth0|random',
    username: 'Louis',
    name: 'TV',
    image: JSON.stringify({
      url: 'http://res.cloudinary.com/receipt-keepers/image/upload/v1658051941/dnoaqqf0j3qptepmxosq.webp',
      public_id: 'dnoaqqf0j3qptepmxosq',
      signature: '37880eb90ac016aaf94af30d47bd407807ff673d',
    }),
    purchaseDate: new Date(08 / 01 / 2022),
    store: 'Harvey Norman',
    price: 2300,
    categoryId: 3,
    categoryType: 'Electronics',
    note: 'Cheap TV',
    warrantyId: 2,
    expiryDate: new Date(08 / 07 / 2022),
    warrantyPeriod: 26,
    warrantyPeriodUnit: 'week(s)',
  },
  {
    id: 3,
    auth0_id: 'auth0|someone',
    username: 'Lauren',
    name: 'Microwave',
    image: JSON.stringify({
      url: 'http://res.cloudinary.com/receipt-keepers/image/upload/v1658051992/tuttn7hdmvpxaggfcppl.jpg',
      public_id: 'tuttn7hdmvpxaggfcppl',
      signature: 'c336638a193d56b64ec43d043da0940c36d71c32',
    }),
    purchaseDate: new Date(10 / 06 / 2021),
    store: 'Noel Leeming',
    price: 3400,
    categoryId: 2,
    categoryType: 'Appliance',
    note: 'Expensive microwave',
    warrantyId: null,
    expiryDate: '',
    warrantyPeriod: '',
    warrantyPeriodUnit: '',
  },
  {
    id: 4,
    auth0_id: 'auth0|somebody',
    username: 'Adam',
    name: 'Computer',
    image: JSON.stringify({
      url: 'http://res.cloudinary.com/receipt-keepers/image/upload/v1658051941/dnoaqqf0j3qptepmxosq.webp',
      public_id: 'dnoaqqf0j3qptepmxosq',
      signature: '37880eb90ac016aaf94af30d47bd407807ff673d',
    }),
    purchaseDate: new Date(25 / 03 / 2022),
    store: 'PB Tech',
    price: 4500,
    categoryId: 4,
    categoryType: 'PC',
    note: 'Gaming computer',
    warrantyId: 4,
    expiryDate: new Date(25 / 03 / 2023),
    warrantyPeriod: 1,
    warrantyPeriodUnit: 'year(s)',
  },
]
